using System;

namespace BattleSystem {
    public delegate void EventOnText(string text, Side side = null);
    public delegate void EventOnStart(DateTime time);
    public delegate void EventOnEnd(DateTime time);
    public delegate void EventOnAttack(Pokemon poke, MoveAction move, Pokemon target);
    public delegate void EventOnSwitch(Pokemon poke);
    public delegate void EventOnHeal(Pokemon poke, int amount, string source);
    public delegate void EventOnDrag(Pokemon poke);
    public delegate void EventOnTurn(int turn);
    public delegate void EventOnWin(Side side);
    public delegate void EventOnTie();
    public delegate void EventOnDamage(Pokemon from, int damage, Pokemon takenBy);
    public delegate void EventOnFaint(Pokemon faint);
    public delegate void EventOnItemUse(Pokemon usedBy);
    public delegate void EventOnItemUseExternal(Pokemon usedBy, string item);
    public delegate void EventOnItemEnd(Pokemon usedBy);
    public delegate void EventOnMega(Pokemon poke);
    public delegate void EventOnZmove(Pokemon poke);
    public delegate void EventOnUltraBurst(Pokemon poke);
    public delegate void EventOnDynamax(Pokemon poke);
    public delegate void EventOnAbility(Pokemon poke);
    public delegate void EventOnField(string condition);
    public delegate void EventOnWeather(string weather);
    public delegate void EventOnSide(Side side, string condition);
    public delegate void EventOnImmune(Pokemon poke);
    public delegate void EventOnStatus(Pokemon poke);
    public delegate void EventOnStatusCure(Pokemon poke, Status status);
    public delegate void EventOnResist(Pokemon poke);
    public delegate void EventOnTransform(Pokemon poke, string to);
    public delegate void EventOnFormChange(Pokemon poke, string form);
    public delegate void EventOnIllusion(Pokemon poke);
    public delegate void EventOnFail(string effect);
    public delegate void EventOnNothing();
    public delegate void EventOnMiss(Pokemon poke, MoveAction move, string reason);
    public delegate void EventOnRecharge(Pokemon poke);
    public delegate void EventOnStatBoost(Pokemon poke, string stat, int amount);
    public delegate void EventOnStatUnboost(Pokemon poke, string stat, int amount);
    public delegate void EventOnStatClear(Pokemon poke, string stat);
    public delegate void EventOnStatClearAll(Pokemon poke);
    public delegate void EventOnPrimal(Pokemon poke);
    public delegate void EventOnPrepare(Pokemon poke, MoveAction move);
    public delegate void EventOnBerryUse(Pokemon poke, string berry);
    public delegate void EventOnStatCopy(Pokemon from, Pokemon by);
    public delegate void EventOnSwapBoost(Pokemon poke1, Pokemon poke2);
    public delegate void EventOnSetBoost(Pokemon poke, string stat, int amount);
    public delegate void EventOnHitCount(Pokemon hitBy, MoveAction move, int count, Pokemon hitOn);
    public delegate void EventOnCritical(Pokemon poke, MoveAction move);
    public delegate void EventOnSuperEffective(Pokemon poke, MoveAction move);
    public delegate void EventOnNoTarget();
    public delegate void EventOnCant(Pokemon poke, string reason);
    public delegate void EventOnStatInvert(Pokemon poke);
    public delegate void EventOnChoice(Side side, string type, bool forced);
}